FROM public.ecr.aws/lambda/python:3.10-x86_64

# Copy function code
ADD serving_api.tar.gz ${LAMBDA_TASK_ROOT}


RUN pip3 install -r requirements.txt --target ${LAMBDA_TASK_ROOT}

##CMD [ "serving_api.lambda_handler" ]


# Set working directory inside container
WORKDIR /app

# Copy the script into the container
COPY train_predict.py .

# Install dependencies inside the container
RUN pip install scikit-learn joblib numpy

# Train and save the model inside the container
RUN python train_predict.py 5.0

# Define default command (overridable when running the container)
CMD ["python", "train_predict.py"]